import { siteAsset } from './paths.js';

const split = (value) => value.split('｜').map((name) => name.trim());

export const chapters = [
  {
    id: 'get-a-life',
    index: '01',
    title: 'GET A LIFE',
    year: '2006',
    period: 'HONG KONG · 2006',
    theme: 'get',
    backdrop: siteAsset('assets/get-a-life.png'),
    cover: 'https://is1-ssl.mzstatic.com/image/thumb/Music113/v4/da/8c/08/da8c0894-4cc9-9774-a6ca-ee4d14c1ab95/06UMGIM30818.rgb.jpg/800x800bb.jpg',
    edition: 'Get A Life (Live) · 3CD',
    label: 'Cinepoly Records Co. Ltd.',
    description: '從《浮誇》開場的聲音，進入 2006 年香港現場發行留下的 38 首曲目。這裡展示的是唱片曲序，不代替每一晚的演出紀錄。',
    feature: '浮誇',
    credits: '2006 · 38 TRACKS · 3 DISCS',
    albumUrl: 'https://music.apple.com/us/album/get-a-life-live/1462045698',
    listenUrl: 'https://open.spotify.com/album/28EFqQxFk44OXnmbVaOHEn',
    mediaUrl: 'https://music.apple.com/us/album/get-a-life-live/1462045698',
    mediaLabel: '查看官方現場影像',
    sourceNote: '官方發行封面與音樂影像；完整現場攝影使用權待核實。',
    discs: [
      split('Overture｜浮誇｜怪物｜心裡有鬼｜兩名男子街頭相遇｜不良嗜好｜Shall We Dance｜三個人的探戈｜孤獨探戈｜活著多好｜怕死'),
      split('爛｜聽聽｜大個女｜單車｜最佳損友｜Shall We Talk｜如果這一秒鐘你跟我講你不愛我｜傷信｜1874｜黑夜不再來'),
      split('美麗有罪｜2001太空漫遊｜打得火熱｜送院途中｜幸災樂禍｜忘記歌詞｜夕陽無限好｜打回原形｜防不勝防｜十面埋伏｜葡萄成熟時｜KING KONG + 超人的主題曲｜明年今日｜K歌之王｜人來人往｜阿牛｜與我常在'),
    ],
    sources: [
      ['Apple Music · 官方現場專輯', 'https://music.apple.com/us/album/get-a-life-live/1462045698'],
      ['Spotify · 完整發行曲序', 'https://open.spotify.com/album/28EFqQxFk44OXnmbVaOHEn'],
      ['YesAsia · 香港現場 3CD 發行資料', 'https://www.yesasia.com/global/%E9%99%B3%E5%A5%95%E8%BF%85-get-a-life-%E6%BC%94%E5%94%B1%E6%9C%83-live-3cd/1004196704-0-0-0-zh_TW/info.html'],
    ],
  },
  {
    id: 'moving-on-stage',
    index: '02',
    title: 'MOVING ON STAGE',
    year: '2007',
    period: 'HONG KONG · 2007',
    theme: 'mos',
    backdrop: siteAsset('assets/mos-stage.jpg'),
    cover: 'https://is1-ssl.mzstatic.com/image/thumb/Music123/v4/63/f1/bb/63f1bb47-2d9f-1bb2-3a9a-5606ff82be7f/contsched.nvwpvcwe.jpg/800x800bb.jpg',
    edition: "Eason's Moving On Stage 1 · 3CD",
    label: 'Cinepoly Records Co. Ltd.',
    description: '從白玫瑰到明年今日，舞台在光與暗之間持續換景。這一章沿 3CD 正式發行曲序前進，影像來自已提供的完整現場版本。',
    feature: '白玫瑰',
    credits: '2007 · 33 TRACKS · 3 DISCS',
    albumUrl: 'https://www.yesasia.com/global/easons-moving-on-stage-1-3cd/1005163950-0-0-0-en/info.html',
    listenUrl: 'https://music.apple.com/us/album/eason-moving-on-stage-1-live/1462045568',
    mediaUrl: 'https://music.apple.com/us/album/eason-moving-on-stage-1-live/1462045568',
    mediaLabel: '查看官方現場專輯',
    sourceNote: '專輯封面來自 Apple Music；本地現場影片由使用者提供。',
    discs: [
      split('Overture｜白玫瑰｜信心花舍｜K歌之王｜裙下之臣｜富士山下｜不如不見｜夕陽無限好｜人車誌｜馬利奧派對｜最佳損友｜What a Wonderful World｜今日｜黑擇明'),
      split('Dance Mix: Shall We Dance/傷信/幸福摩天輪/美麗有罪/2001太空漫遊/給愛麗斯｜熱島小夜曲｜Crying in the Party｜我不好愛｜打回原形｜衝口而出｜月球上的人｜葡萄成熟時｜浮誇｜低等動物｜粵語殘片'),
      split('淘汰｜黃金時代｜落花流水｜第五個現代化｜演唱會｜天下無雙｜與我常在｜明年今日'),
    ],
    sources: [
      ['3CD 實體發行曲序', 'https://www.yesasia.com/global/easons-moving-on-stage-1-3cd/1005163950-0-0-0-en/info.html'],
      ['Apple Music · 官方數碼發行', 'https://music.apple.com/us/album/eason-moving-on-stage-1-live/1462045568'],
    ],
  },
  {
    id: 'duo',
    index: '03',
    title: 'DUO',
    year: '2010',
    period: 'HONG KONG · 2010',
    theme: 'duo',
    backdrop: siteAsset('assets/duo-stage.jpg'),
    cover: 'https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/33/e9/ac/33e9ac40-2153-dcd1-6910-5d5ed3270228/00602488994040.rgb.jpg/800x800bb.jpg',
    edition: '陳奕迅2010 Duo演唱會 · 3CD',
    label: 'Cinepoly Records Co. Ltd.',
    description: '兩面聲音在同一段現場紀錄中交錯。他人的作品與自己的歌並列，熟悉的曲名被重新放進另一種順序。',
    feature: '陀飛輪',
    credits: '2010 · 38 TRACKS · 3 DISCS',
    albumUrl: 'https://music.apple.com/us/album/%E9%99%B3%E5%A5%95%E8%BF%852010-duo%E6%BC%94%E5%94%B1%E6%9C%83/1442966677',
    listenUrl: 'https://music.apple.com/us/album/%E9%99%B3%E5%A5%95%E8%BF%852010-duo%E6%BC%94%E5%94%B1%E6%9C%83/1442966677',
    mediaUrl: 'https://music.apple.com/us/album/%E9%99%B3%E5%A5%95%E8%BF%852010-duo%E6%BC%94%E5%94%B1%E6%9C%83/1442966677',
    mediaLabel: '查看官方現場影像',
    sourceNote: '專輯封面來自 Apple Music；DUO Disc 1 本地影片由使用者提供。',
    discs: [
      split('今天等我來｜好歌獻給你｜落花流水｜囍帖街｜七百年後｜約定｜寂寞夜晚｜浮誇｜禁色｜無人之境｜破曉｜夕陽無限好'),
      split('人車誌｜裙下之臣｜陀飛輪｜沙龍｜葡萄成熟時｜Medley: 熱辣辣/反斗星/頭髮亂了/好戲在後頭｜芳華絕代｜不來也不去｜富士山下｜與我常在｜我的快樂時代'),
      split('歌.頌｜PG家長指引｜那一夜有沒有說｜反高潮｜一絲不掛｜單車｜等｜Mr. Lonely｜我甚麼都沒有｜抱擁這分鐘｜The End of the World｜我的世界末日｜每一個明天｜明年今日｜Every Time We Say Goodbye'),
    ],
    sources: [
      ['Apple Music · 官方現場專輯與影像', 'https://music.apple.com/us/album/%E9%99%B3%E5%A5%95%E8%BF%852010-duo%E6%BC%94%E5%94%B1%E6%9C%83/1442966677'],
      ['YesAsia · 3CD 完整發行曲序', 'https://www.yesasia.com/us/duo-eason-chan-concert-live-2010-3cd/1022885926-0-0-0-en/info.html'],
      ['香港演出日期 · 公共紀錄', 'https://www.legco.gov.hk/yr14-15/english/counmtg/hansard/cm20150624-translate-e.pdf'],
    ],
  },
  {
    id: 'easons-life',
    index: '04',
    title: 'EASON’S LIFE',
    year: '2013',
    period: 'HONG KONG · 2013',
    theme: 'life',
    backdrop: siteAsset('assets/duo.png'),
    cover: 'https://is1-ssl.mzstatic.com/image/thumb/Music128/v4/ee/a5/65/eea565b2-9b4a-2fa7-cdac-fa48c8e1f74f/00602488968980.rgb.jpg/800x800bb.jpg',
    edition: 'Eason’s Life 2013演唱會 · 2CD',
    label: 'Eas Music Ltd.',
    description: '從《今天只做一件事》到《主旋律》，官方發行曲序像一天的刻度，將現場的時間感一行行留下。',
    feature: '今天只做一件事',
    credits: '2013 · 21 TRACKS · 2 DISCS',
    albumUrl: 'https://music.apple.com/us/album/easons-life-2013%E6%BC%94%E5%94%B1%E6%9C%83/1443270803',
    listenUrl: 'https://music.apple.com/us/album/easons-life-2013%E6%BC%94%E5%94%B1%E6%9C%83/1443270803',
    mediaUrl: 'https://www.yesasia.com/us/easons-life-concert-live-2013-2dvd/1034834715-0-0-0-en/info.html',
    mediaLabel: '查看官方 DVD 發行資料',
    sourceNote: '官方發行封面、DVD／海報資料；完整現場攝影使用權待核實。',
    discs: [
      split('今天只做一件事｜L.I.F.E. Overture｜花花世界｜Life Goes On｜每一個明天｜美滿人生｜Welcome To The Future｜時代巨輪｜大人｜碌卡'),
      split('Stranger Under My Skin｜幸福摩天輪｜信任｜時光倒流二十年｜夕陽無限好｜今日｜我的快樂時代｜天下無雙｜與我常在｜床頭床尾｜主旋律'),
    ],
    sources: [
      ['Apple Music · 官方現場專輯', 'https://music.apple.com/us/album/easons-life-2013%E6%BC%94%E5%94%B1%E6%9C%83/1443270803'],
      ['環球唱片 DVD · 節目次序與影像資訊', 'https://www.yesasia.com/us/easons-life-concert-live-2013-2dvd/1034834715-0-0-0-en/info.html'],
      ['香港體育館 · 2013 年活動日曆', 'https://www.lcsd.gov.hk/en/hkc/common/form/hkc_2013_8_calendar.pdf'],
    ],
  },
  {
    id: 'fear-and-dreams',
    index: '05',
    title: 'FEAR AND DREAMS',
    year: '2022—2025',
    period: 'WORLD TOUR · 2022—2025',
    theme: 'fear',
    backdrop: siteAsset('assets/fear-and-dreams.png'),
    cover: 'https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/9b/ac/5d/9bac5de2-fcd3-76a2-850c-38a3a9a44f8d/25UM1IM06806.rgb.jpg/800x800bb.jpg',
    edition: 'FEAR and DREAMS (Live) · 2CD',
    label: 'Eas Music Ltd. / Universal Music',
    description: '官方 2CD 將演出分成兩段。由 Fear 向 Dreams 推進的概念來自唱片公司的作品介紹；這裡的藍金光影是策展詮釋。',
    feature: '人神鬥',
    credits: '2025 RELEASE · 31 TRACKS · 2 DISCS',
    albumUrl: 'https://www.umusic.com.tw/album.php?q=N2j0Q226M-Q0E9AE9E9AE-',
    listenUrl: 'https://music.apple.com/us/album/fear-and-dreams-live/1831490372',
    mediaUrl: 'https://www.youtube.com/watch?v=mUfov5kFIS4',
    mediaLabel: '觀看官方巡演紀錄片預告',
    sourceNote: '官方唱片封面、藝人頻道影片與持有人授權的 2025 香港演唱會影像；攝影書照片的網頁使用權待核實。',
    discs: [
      split('mozart’s requiem in d minor｜2001太空漫遊｜人神鬥｜當這地球沒有花｜謊言｜時代巨輪｜想聽｜黑洞｜龍舌蘭｜異夢｜如果這一秒鐘你跟我講你不愛我｜黑夜不再來｜開不了心｜告別娑婆｜完｜今日'),
      split('夢的可能｜一個靈魂的獨白｜任我行｜the world is actually bigger｜人生馬拉松｜請相信我｜四季｜常在 ∙ 忘記｜life goes on｜大人｜致明日的舞｜七百年後｜幸福摩天輪｜我們萬歲｜i’d live it all over again'),
    ],
    sources: [
      ['環球唱片 · 官方 2CD 曲序與巡演說明', 'https://www.umusic.com.tw/album.php?q=N2j0Q226M-Q0E9AE9E9AE-'],
      ['Apple Music · 官方數碼發行', 'https://music.apple.com/us/album/fear-and-dreams-live/1831490372'],
      ['陳奕迅官方頻道 · 紀錄片預告', 'https://www.youtube.com/watch?v=mUfov5kFIS4'],
      ['藝人官方網站 · 巡演資料', 'https://www.easonchan.net/hk/about-e/?lang=en'],
    ],
  },
];

export const totalTracks = chapters.reduce(
  (sum, chapter) => sum + chapter.discs.reduce((discSum, disc) => discSum + disc.length, 0),
  0,
);
